version: "3"

services:
  tg_bot:
    build: tg_bot/
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    environment:
      - TG_TOKEN=${TG_TOKEN} # токен telegram бота
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных
      - FUNCTIONS_API_URL=http://functions_api/api/
      - EXAMS_API=${EXAMS_API}

  vk_bot:
    build: vk_bot/
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    environment:
      - VK=${VK_TOKEN} # токен telegram бота
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных
      - FUNCTIONS_API_URL=http://functions_api/api/
      - EXAMS_API=${EXAMS_API}

  notification_service:
    build: notification_service/
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    environment:
      - TG_TOKEN=${TG_TOKEN} # токен telegram бота
      - VK_TOKEN=${VK_TOKEN} # токен VK бота
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных
      - FUNCTIONS_API_URL=http://functions_api/api/

  getting_schedule:
    build: getting_schedule/
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    environment:
      - MONGO_DB_ADDR=mongodb # адрес mongoDB
      - MONGO_DB_PORT=27017 # порт mongoDB (default: 27017)
      - MONGO_DB_DATABASE=Smart_schedule_IRNITU # название базы данных MongoDB (default: Smart_schedule_IRNITU)
      - PG_DB_DATABASE=${PG_DB_DATABASE} # название базы данных PostgreSQL (default: schedule)
      - PG_DB_USER=${PG_DB_USER} # пользователь PostgreSQL
      - PG_DB_PASSWORD=${PG_DB_PASSWORD}  # пароль PostgreSQL
      - PG_DB_HOST=${PG_DB_HOST} # адрес PostgreSQL
      - PG_DB_PORT=5432 # порт PostgreSQL (default: 5432)
      - GETTING_SCHEDULE_TIME_HOURS=1 # время задержки (в часах) между обращениями к PostgreSQL для получения расписания (default: 1)
      - EXAMS_API=${EXAMS_API}

  functions_api:
    build: functions_api/
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always


  mongodb:
    image: mongo:latest
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    volumes:
      - ./data/db:/data/db
    restart: always
